# Generated by Django 3.1.3 on 2020-12-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditemsmodel',
            name='table_id',
            field=models.CharField(max_length=10),
        ),
    ]
