# Generated by Django 3.1.3 on 2020-12-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0002_auto_20201214_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditemsmodel',
            name='itemname',
            field=models.CharField(choices=[('orange', 'orange'), ('pineapple', 'pineapple'), ('juice', 'juice')], default='empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='fooditemsmodel',
            name='table_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
